version: '3'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - 8000:8000
#    depends_on:
#      - nginx
    environment:
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    command: bash -c "cd .. && python3 -m venv .envtest && source .envtest/bin/activate && cd code && pip install -r requeriments.txt && uvicorn Buscancun.asgi:application --host 0.0.0.0 --port 8000"
  nginx:
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ./server:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - django
#    command: service nginx start
