version: '3'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    command: ["sh", "-c", "python manage.py migrate && python manage.py collectstatic --noinput &&supervisord -n"]
  nginx:
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ./server:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - django
#    command: service nginx start
