# Generated by Django 3.2 on 2023-06-29 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chofer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autobus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('numero_placa', models.CharField(max_length=20)),
                ('capacidad_pasajeros', models.PositiveIntegerField(default=60, verbose_name='Capacidad')),
                ('asientos_disponibles', models.PositiveIntegerField(default=0, verbose_name='Asientos Disponibles')),
                ('capacidad_asientos', models.PositiveIntegerField(default=40)),
                ('activo', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('EN ESPERA', 'EN ESPERA'), ('ABORDANDO', 'ABORDANDO'), ('SALIENDO', 'SALIENDO'), ('EN VIAJE', 'EN VIAJE'), ('LLEGANDO', 'LLEGANDO')], default='EN ESPERA', max_length=25)),
            ],
            options={
                'verbose_name': 'Autobus',
                'verbose_name_plural': 'Autobuses',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterModelOptions(
            name='chofer',
            options={'ordering': ('-id',), 'verbose_name': 'Chofer', 'verbose_name_plural': 'Choferes'},
        ),
        migrations.AddField(
            model_name='chofer',
            name='autobus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chofer.autobus'),
        ),
    ]
